# Criação de Matriz

NumPy é o pacotefundamental para computação númerica com Python. Ele fornece maneiras poderosas de criar, armazenar e manipular dados, o que o torna capaz de se integrar de forma perfeita e rápida a uma ampla variedade de bancos de dados e formatos de dados. Essa também é a base sobre a qual o Pandas se baseia, que é um pacote centrado em dados de alto desempenho. 

Vamos criar matrizes com determinados tipos de dados, manipular matrizes, selecionar elementos de matrizes e carregar conjuntos de dados em matrizes. 

Essas funções são úteis para manipular dados e entender as funcionalidades de outros pacotes de dados comuns do Python.

In [1]:
# A abreviatura comum do NumPy é "np"

# Bibliotecas
import numpy as np
import math

#### Criação de Array

In [ ]:
# As matrizes são exibidas como uma lista ou lista de listas e também podem ser criadas por meio de listas.
# Ao criar um vetor, passamos para ele uma lista como argumento em uma lista numérica.

a = np.array([1, 2, 3])
print(a)

# Podemos imprimir o número de dimensões de uma lista usando:
print(a.ndim)

[1 2 3]
1


In [18]:
# Se passarmos uma lista de listas para um vetor numpy, criaremos um vetor multidimensional, por exemplo, uma matriz.
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)
print(b.ndim)

[[1 2 3]
 [4 5 6]]
2


In [9]:
# Podemos imprimir o comprimento de cada dimensão chamando o atributo shape, que retorna uma tupla:
b.shape

(2, 3)

In [ ]:
# Também podemos verificar o tipo de itens na matriz, então um dtype.
a.dtype


dtype('int64')

In [21]:
# Além dos números inteiros, os floats também são aceitos nas matrizes numpy
c = np.array([2.2, 5, 1.1])
c.dtype.name

'float64'

In [22]:
# Vamos ver os dados em nosso vetor
c

array([2.2, 5. , 1.1])

Perceba que o numpy converte automaticamente números inteiros, como 5, até pontos flutuantes. Como não há perda de precisão, o numpy tentará fornecer o melhor formato de tipo de dados possível para manter seus tipos de dados homogêneos, o que significa que eles são todos iguais na vetor.

OBS: Por isso quando colocamos uma str no vetor, TODOS os outros dados terão o tipo de dado mais geral entre os vetores. 

In [27]:
# As vezes, sabemos a forma de um vetor/matriz que queremos criar, mas não o que queremos que esteja nela.
# O numpy oferece várias funções para criar matrizes com espaços reservados iniciais, como zeros ou uns. 
# Vamos criar duas matrizes, ambas com a mesma forma, mas com valores de preenchimento diferentes. 

d = np.zeros((2, 3), int)
print(d)

e = np.ones((2, 3))
print(e)

[[0 0 0]
 [0 0 0]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [41]:
# Também podemos gerar uma matriz com números aleatórios.
f1 = np.random.rand(2, 3)

# Se fosse inteiros:
f2 = np.random.randint(0, 10, (2, 3))

print(f1)
print('\n', f2)

[[0.37012286 0.62993629 0.23023623]
 [0.14678558 0.44380166 0.9075451 ]]

 [[2 3 3]
 [5 9 6]]


In [ ]:
# Também podemos criar uma sequência de números em uma matriz com a função de arranjo. O primeiro argumento é o limite inicial, o segundo argumento é o limite final - 1 e o terceiro argumento é a diferença entre cada número consecutivo.

# Vamos criar um vetor de todos os números pares de 10 até 49.
g = np.arange(10, 50, 2)
print(g)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
# Vamos dar uma olhada em G.Se quisermos gerar uma sequência de pontos flutuantes, usamos a função linspace(). 
# O terceiro argumento não é a diferença entre dois números, mas é o número total de itens que você deseja gerar. 
h = np.linspace(0, 2, 15) # 15 números entre 0 a 2, incluindo o 0 e o 2.
print(h)

[0.         0.14285714 0.28571429 0.42857143 0.57142857 0.71428571
 0.85714286 1.         1.14285714 1.28571429 1.42857143 1.57142857
 1.71428571 1.85714286 2.        ]
