# Indexação, fatiamento e iteração

In [1]:
import numpy as np

#### Indexação

In [2]:
# Vamos criar um vetor
a = np.array([1, 2, 3, 4, 5, 6, 7])
a[2]

np.int64(3)

In [3]:
# Para vetores multidimensionais, precisamos usar a indexação de matrizes inteiras. 
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)
a[1][1]

[[1 2]
 [3 4]
 [5 6]]


np.int64(4)

In [ ]:
# Podemos criar uma nova matriz, e nela vamos passar uma lista e, dessa lista, estamos na verdade pegando nossa outra matriz e retirando os valores nos quais estamos interessados
np.array([a[0, 0], a[1, 1], a[2, 1]])


array([1, 4, 6])

In [6]:
# Também podemos fazer isso usando outra forma de indexação de matrizes, na qual basicamente compacta a primeira lista e a segunda. 
print(a[[0, 1, 2], [0, 1, 1]])

# Perceba que nesse caso, está pegando como se fosse pares ordenados de uma lista e da outra

[1 4 6]


#### Indexação booleana

In [7]:
# A indexação booleana nos permite selecionar elementos arbitrários com base nas condições. 
print(a > 5)

[[False False]
 [False False]
 [False  True]]


In [ ]:
# Podemos colocar essa matriz de valores booleanos, como uma máscara booleana, sobre a matriz original para retornar uma matriz unidimensional relacionada aos valores reais
print(a[a > 5])

# O que está acontecendo aqui é que pegaremos o operador maior que cinco e transmitiremos isso. Então será comparado isso em todos os elementos de "a", criando uma nova matriz com apenas os valores que satisfazem a condição.  
# Ao usar essa máscara booleana para indexar o array original, você está filtrando os valores que atendem à condição (> 5). Ou seja, você pega os valores da matriz onde a condição é True.

[6]


#### Fatiamento

In [10]:
# Fatiar é uma forma de criar uma submatriz com base na matriz original. Para vetores unidimensionais, o fatiamento funciona de forma semelhante a uma lista. 
a = np.array([0, 1, 2, 3, 4, 5, 6, 7])

# Pegando do índice 0 até o 2
print(a[:3])

# Pegando do índice 2 até o 4
print(a[2:5])

[0 1 2]
[2 3 4]


In [48]:
# Para matrizes multidimensionais, funciona de forma semelhante
a = np.random.randint(0, 100, (10, 5))
print(a)



[[27  5 53 67 40]
 [71  6 95 78 12]
 [72 43 50 28 36]
 [14 18 44 61 20]
 [34 77 28 11 48]
 [26 57 73 13 30]
 [19 58 53  1 34]
 [78 88 93  7 73]
 [30 19 11 42 78]
 [ 5 89 67 48  1]]


In [49]:
# Quando fazemos a[0], estamos pegando a primeira linha inteira, então se fizermos a[:n], estaremos pegando da linha 0 até a linha 'n'
print(a[:2])

print()

# Pegando da linha 4 até a linha 10
print(a[4:10]) 

[[27  5 53 67 40]
 [71  6 95 78 12]]

[[34 77 28 11 48]
 [26 57 73 13 30]
 [19 58 53  1 34]
 [78 88 93  7 73]
 [30 19 11 42 78]
 [ 5 89 67 48  1]]


In [50]:
# Quando fazemo a[0][0], estamos pegando o primeiro item da primeira coluna, então se fizermos a[0][:n] estaremos fatiando na coluna, ou seja, seria da linha 0 pegar os valores de 0 até n - 1. Por exemplo: 

print(a[0][:4])
print()
print(a[4][:2])

[27  5 53 67]

[34 77]


In [51]:
# Seguindo nessa lógica pensamos que ao fazer a[:4][:2] estaremos fatiando a linha e a coluna, porém muito CUIDADO, pois NÃO ESTAREMOS FATIANDO NA COLUNA (que seria andar na linha), o que acontece na realidade é o fatiamento do fatiamento, por exemplo:
print(a[:4])
print()
print(a[:4][1:3])

# Nesse caso, pegamos as linhas 0 até 3, e dessas 4 linhas pegadas, fizemos um novo fatiamento pegando da 1 até 2

[[27  5 53 67 40]
 [71  6 95 78 12]
 [72 43 50 28 36]
 [14 18 44 61 20]]

[[71  6 95 78 12]
 [72 43 50 28 36]]


In [52]:
print(f'{a}\n')

# Para fazer o fatiamento de linhas e colunas ao mesmo tempo, usa-se: 
print(a[:8, 1:3])

# Aqui pegamos da linha 0 até a linha 7, e dessas linhas pegamos os valores das colunas 1 (segunda) e 2 (terceira)

[[27  5 53 67 40]
 [71  6 95 78 12]
 [72 43 50 28 36]
 [14 18 44 61 20]
 [34 77 28 11 48]
 [26 57 73 13 30]
 [19 58 53  1 34]
 [78 88 93  7 73]
 [30 19 11 42 78]
 [ 5 89 67 48  1]]

[[ 5 53]
 [ 6 95]
 [43 50]
 [18 44]
 [77 28]
 [57 73]
 [58 53]
 [88 93]]


É importante se atentar que modificar a submatriz também modificará a matriz original, já que os valores são passados por referência.

Exemplo:

In [53]:
# Matriz original antes
print(a, '\n')

# sub matriz 
sub_matriz = a[:2, 1:3]
print(sub_matriz, '\n')

sub_matriz[0][0] = 1000

# Matriz original depois
print(a)

[[27  5 53 67 40]
 [71  6 95 78 12]
 [72 43 50 28 36]
 [14 18 44 61 20]
 [34 77 28 11 48]
 [26 57 73 13 30]
 [19 58 53  1 34]
 [78 88 93  7 73]
 [30 19 11 42 78]
 [ 5 89 67 48  1]] 

[[ 5 53]
 [ 6 95]] 

[[  27 1000   53   67   40]
 [  71    6   95   78   12]
 [  72   43   50   28   36]
 [  14   18   44   61   20]
 [  34   77   28   11   48]
 [  26   57   73   13   30]
 [  19   58   53    1   34]
 [  78   88   93    7   73]
 [  30   19   11   42   78]
 [   5   89   67   48    1]]


Em lista, faziamos um fatiamento para copiar os valors, por exemplo:

b = a[:] 
Assim é uma cópia de "a" dentro de "b"

Porém aqui, para copiar, usa-se como dicionários, com .copy()

In [55]:
# Matriz original antes
print(a, '\n')

# sub matriz 
sub_matriz = a[:2, 1:3].copy()
print(sub_matriz, '\n')

sub_matriz[0][0] = 9999
print(sub_matriz, '\n')

# Matriz original depois
print(a)


[[  27 1000   53   67   40]
 [  71    6   95   78   12]
 [  72   43   50   28   36]
 [  14   18   44   61   20]
 [  34   77   28   11   48]
 [  26   57   73   13   30]
 [  19   58   53    1   34]
 [  78   88   93    7   73]
 [  30   19   11   42   78]
 [   5   89   67   48    1]] 

[[1000   53]
 [   6   95]] 

[[9999   53]
 [   6   95]] 

[[  27 1000   53   67   40]
 [  71    6   95   78   12]
 [  72   43   50   28   36]
 [  14   18   44   61   20]
 [  34   77   28   11   48]
 [  26   57   73   13   30]
 [  19   58   53    1   34]
 [  78   88   93    7   73]
 [  30   19   11   42   78]
 [   5   89   67   48    1]]
